# Generated by Django 5.0.2 on 2024-02-08 05:22

import django.db.models.deletion
import icases.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Service', 'Service'), ('Equipment', 'Equipment'), ('Instrument', 'Instrument'), ('Consumable', 'Consumable'), ('Others', 'Others')], default='Draft', max_length=20)),
                ('description', models.TextField()),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxcode', models.CharField(max_length=100)),
                ('taxrate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Opened', 'Opened'), ('Closed', 'Closed')], default='Opened', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ICase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Normal', 'Normal'), ('Big', 'Big')], default='Normal', max_length=20)),
                ('target_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('bodypart', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Draft', max_length=100)),
                ('tags', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('appointed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_start', models.DateTimeField(blank=True, null=True)),
                ('case_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_icases', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_icases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ICaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=icases.models.upload_to_icase_id_folder)),
                ('part', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('bodypart', models.CharField(choices=[('1', '01'), ('2', '02'), ('3', '03'), ('4', '04'), ('5', '05'), ('6', '06'), ('7', '07'), ('8', '08'), ('9', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('Others', 'Others')], default='Others', max_length=10)),
                ('filetype', models.CharField(default='', max_length=100)),
                ('modality', models.CharField(choices=[('IO Camera', 'IOCam'), ('IO Xray', 'IOXray'), ('Panoramic', 'Pano'), ('CBCT', 'CBCT'), ('Cephalometric', 'Ceph'), ('Camera', 'Camera'), ('Others', 'Others')], default='IOCam', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icases.icase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ICaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icases.icase')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icases.product')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terms', models.IntegerField()),
                ('visits', models.IntegerField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Processing', 'Processing'), ('Closed', 'Closed')], default='Draft', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icases.icase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TPlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodypart', models.CharField(max_length=100)),
                ('treatmentcode', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxcode', models.CharField(max_length=100)),
                ('taxrate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sortingorder', models.IntegerField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Processing', 'Processing'), ('Closed', 'Closed')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icases.tplan')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
